// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ejnatxuuqjufmujjgoxr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVqbmF0eHV1cWp1Zm11ampnb3hyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk0NDIxOTksImV4cCI6MjA4NTAxODE5OX0.QBFZUlzFwHFeMCKKwG6jTnuoZTxsvzQJ-59wbs6gPk8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});